{
 "title": "Indoor Air Quality",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "Temperature",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"indoor_temperature\" and\n    r.host == \"r-xps\"\n  )"
    }
   ]
  },
  {
   "title": "Humidity",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "humidity" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"indoor_humidity\" and\n    r._field == \"humidity\"\n  )"
    }
   ]
  },
  {
   "title": "Pressure",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "pressurehpa" } },
   "targets": [
    {
     "query": "from(bucket: \"iaq-bucket\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._measurement == \"air_pressure\" and\n    r.host == \"r-xps\"\n  )"
    }
   ]
  },
  { "title": "CO2", "type": "timeseries", "gridPos": { "h": 9, "w": 8, "x": 8, "y": 12 } },
  { "title": "TVOC", "type": "timeseries", "gridPos": { "h": 9, "w": 8, "x": 16, "y": 12 } }
 ]
}